version: "3.9"

services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    ports:
      - "80:8000"
    depends_on:
      - app
    networks:
      - internal
    volumes:
      - .:/var/www/html

  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    depends_on:
      - db
    networks:
      - internal
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0.27
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    ports:
      - '3306:3306'
    networks:
      - internal
    volumes:
      - mysql-data:/var/lib/mysql/

volumes:
  mysql-data:

networks:
  internal:
    external: false
